# Generated by Django 5.0.1 on 2024-02-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_booking_case_remove_booking_u_remove_case_u_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_card_details_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('card_holder_name', models.CharField(max_length=20, null=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('pin', models.CharField(max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.tbl_cust')),
            ],
        ),
    ]
