# Generated by Django 5.0.1 on 2024-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paid',
            field=models.CharField(choices=[('paid', 'paid'), ('rejected', 'rejected'), ('not-paid', 'not-paid')], default='not-paid', max_length=20),
        ),
    ]
