# Generated by Django 5.0.1 on 2024-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_booking_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
