# Generated by Django 5.0.1 on 2024-01-19 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_fname', models.CharField(max_length=20)),
                ('S_lname', models.CharField(max_length=20)),
                ('S_email', models.EmailField(default='', max_length=254)),
                ('S_gen', models.CharField(default='', max_length=10)),
                ('S_dob', models.DateField()),
                ('S_ph', models.CharField(max_length=10)),
                ('S_state', models.CharField(default='', max_length=30)),
                ('S_city', models.CharField(max_length=10)),
                ('S_dist', models.CharField(max_length=30)),
                ('S_pin', models.CharField(max_length=10)),
                ('S_status', models.BooleanField()),
                ('S_pass', models.CharField(max_length=20)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
