# Generated by Django 5.0.1 on 2024-01-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0003_alter_tbl_adv_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_adv',
            name='Adv_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_adv',
            name='Adv_experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_adv',
            name='Adv_image',
            field=models.ImageField(null=True, upload_to='Adv_images'),
        ),
    ]
