# Generated by Django 5.0.1 on 2024-01-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0006_tbl_adv_adv_subcategory_alter_tbl_adv_adv_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_adv',
            name='Adv_spec',
        ),
    ]
